name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # or any version you use

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          echo "Setting environment variables..."
          # Loop through all the secrets and export them
          for secret in $(printenv | grep 'GITHUB_SECRET_' | cut -d '=' -f 1); do
            echo "$secret=${!secret}" >> $GITHUB_ENV
          done
          
          # Build the project
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust according to your build output
